### ISSUE TITLE
Where is the scan of Box 1, Folder 13, (Computation Center budget Rockefeller)?

### ISSUE THREAD

**Issue by srisi** [dhmit/computation_hist#104]
Folder 1.13 seems to be the only one missing on Google Drive. Does anyone know what happened to it? @elenaboal maybe?

**Comment by srisi** [comment]
Update: actually, 22-26 and 28 are also missing in the first box so this is probably not urgent.

**Comment by elenaboal** [comment]
Everything that was uploaded from the flash drive, I put into the google drive into its folder.

**Comment by srisi** [comment]
Thanks. Your organization of the drive folder has been extremely useful.

**Comment by srisi** [comment]
(Closed) Opened a more general issue: https://github.com/dhmit/computation_hist/issues/108
