### ISSUE TITLE
Assemble metadata

### ISSUE THREAD

**Issue by srisi** [dhmit/computation_hist#107]
We need help from everyone in the lab in assembling the metadata of our corpus.
You can find a guide on how to enter metadata here: https://github.com/dhmit/computation_hist/blob/master/computation_hist/documentation/metadata.md 
However, if you're new in the lab, feel free to ask one of the continuing lab members to show you what to do--there are a lot of edge cases.

**Comment by felixtran39** [comment]
Working on it!

**Comment by mscuthbert** [comment]
Right now, we're asking everyone to choose a folder and start making metadata for that.  Estimate that 100 documents per person will get it done.

**Comment by mscuthbert** [comment]
(GREAT WORK!)
