### ISSUE TITLE
create an advanced search webpage

### ISSUE THREAD

**Issue by Carol217** [dhmit/computation_hist#110]
create an advanced search option that allows you to look search model fields (author, document, folder, etc) for specific inputs. Ex: search for 'Verzuh' in recipient field only.

AND/OR

create a filter-able page of texts (ex: by adjusting preferred page length, so only documents with 3 or more pages show up, etc)

**Comment by elenaboal** [comment]
I think we should try to make an advanced search page that can stand alone without any user input. We would put a button in the navbar that said "Advanced Search" to link to it

**Comment by mscuthbert** [comment]
Do you mean like a faceted search?

**Comment by ltagliaferri** [comment]
If #149 solves this we should close this issue

**Comment by Carol217** [comment]
yep it does
