### ISSUE TITLE
Recognizing Similar Names

### ISSUE THREAD

**Issue by angcast** [dhmit/computation_hist#113]
Optimally, this will be best in the importing metadata step. Names that are similar in nature will be modified to the correct name. I noticed there are different variations in the same name. 

For example: 

"Morse, Philip M."
"Morse, Philip"

This function will identify those two names as being the same and modify the second one to Morse, Philip M. 

Another example: a person accidentally spelled "Phillip" instead of "Philip" this function will recognize that they are the same person.

**Comment by equationcrunchor** [comment]
This is still relevant: There are currently 12 versions of F. J. Corbato under the People listing.

**Comment by ryaanahmed** [comment]
As of #322 , we've now caught about as much of this as we can programmatically. There still remains a little bit of manual correction to do, but that's captured in https://github.com/dhmit/computation_hist/issues/247, so I'm closing this. 

Great work by a bunch of folks on different parts of this issue!
