### ISSUE TITLE
Let IBM 704 simulator Handle Operations with Negative Codes

### ISSUE THREAD

**Issue by equationcrunchor** [dhmit/computation_hist#143]

**Comment by srisi** [comment]
Can you write a bit more where / which operations with negative codes need to be handled? 
That is: make sure to include enough information that other lab members can jump in and solve the issue.

**Comment by equationcrunchor** [comment]
It's because of how the manual represents operations; it's octal but with a weird sign bit.  With the code converting the negative operation codes will probably cause problems.  More on this [here](
http://bitsavers.org/pdf/ibm/704/24-6661-2_704_Manual_1955.pdf).

**Comment by equationcrunchor** [comment]
Just going to manually change opcodes that are negative; apparently Javascript can't use negative numbers for keys of dictionaries.
