### ISSUE TITLE
Navbar Design

### ISSUE THREAD

**Issue by equationcrunchor** [dhmit/computation_hist#145]
How should we design the navbar(s?) for the Digital Archive, Simulations, and other parts of the site?

**Comment by elenaboal** [comment]
Also, working on this

**Comment by elenaboal** [comment]
Working on this in the navbar branch

**Comment by felixtran39** [comment]
I think this issue has been resolved for now. Navbar now has a dropdown menu for archives and a link to simulations to accomodate for both parts of our site.

**Comment by felixtran39** [comment]
fixed in pull requests #179 #180
