### ISSUE TITLE
Create a document display page

### ISSUE THREAD

**Issue by srisi** [dhmit/computation_hist#160]
We need a page that displays both the document pdf and the document metadata.

**Comment by ifeife123** [comment]
Displaying PDF works - created a branch on 'document_webpage'

**Comment by Mayowa99** [comment]
The current pdf viewer set up with the stuff at the side doesn't work for some of the folders, I'll look into it to see what's happening

**Comment by Mayowa99** [comment]
Made the metadata table into a sidenav bar and made it smaller so that there is more emphasis on the actual doc. Changed some aesthetic parts of the table. Going to work on getting the date to show up in the table. Also, just curious, what is the purpose of the pages section?

**Comment by ifeife123** [comment]
I'm not sure what the purpose of the pages section but I'd just leave it there for now. Should we use a sidenav? I'm not sure if it's "correct" to have two different navbars on one page. But then again it looks nice?

**Comment by Mayowa99** [comment]
I don't think there should be any issue with using two navbars, Stephen also said it was fine. I think the pages might actually be a misinterpretation of the picture drawn on the board, perhaps. When I originally drew that picture there were supposed to be links to the next document on the bottom, but it's possible somebody took my labelless rectangles for pages, lol. I'll leave them up for another day and if nobody has any complaints I'll take them down

**Comment by mscuthbert** [comment]
I do notice that we have navbars w/ two different fonts.  this might be a separate issue, but something to fix.

**Comment by mscuthbert** [comment]
Specific remaining problems can go into their own issues.
