### ISSUE TITLE
Create a timeline

### ISSUE THREAD

**Issue by ltagliaferri** [dhmit/computation_hist#161]
Create an interactive timeline that captures the dates of the various documents in our archive.

Possible model: https://www.darwinproject.ac.uk/letters/darwins-letters-timeline

**Comment by ltagliaferri** [comment]
@rikitabansal Is this what you are working on?

**Comment by mscuthbert** [comment]
Updates on this @rikitabansal and @mgallegos3015 ?

**Comment by rikitabansal** [comment]
@ltagliaferri @mscuthbert Yes! It is not very "interactive" but it has the documents categorized by year and all the documents are linked

**Comment by srisi** [comment]
Re-opening for the moment:
@rikitabansal : Can you finish the timeline tomorrow and open a PR? (Or is this already merged?)
I think the display could be useful to add under the Archives header as "Documents" so visitors could look over a list of all available documents. Toughts?

**Comment by ryaanahmed** [comment]
> I think the display could be useful to add under the Archives header as "Documents" so visitors could look over a list of all available documents. Toughts?

I agree - let's put the link there.

**Comment by ryaanahmed** [comment]
done via https://github.com/dhmit/computation_hist/pull/391

Great work @rikitabansal !
