### ISSUE TITLE
Survey similar sites for design possibilities

### ISSUE THREAD

**Issue by erica02139** [dhmit/computation_hist#173]
Looking at further, related projects might provide more ideas for features and layout.

Some examples could be:

Mapping the Republic of Letters (Stanford):
http://republicofletters.stanford.edu

Six Degrees of Francis Bacon:
http://www.sixdegreesoffrancisbacon.com/?ids=10000473&min_confidence=60&type=network

"Mitford's Worlds," in Digital Mitford: The Mary Russell Mitford Archive:
http://digitalmitford.org/visual.html

Vincent van Gogh: The Letters:
http://vangoghletters.org/vg/

Will keep adding to this list!

**Comment by felixtran39** [comment]
I think a mapping of people would be cool like in Six Degrees of Francis Bacon and "Mitford's Worlds," in Digital Mitford: The Mary Russell Mitford Archive. Maybe one of the most reoccuring people such as Verzuh, F. M. or Morse, P. M.

**Comment by erica02139** [comment]
@felixtran39, a great person to discuss this with would be Scott Weingart, who's speaking at the DHLab this Thursday at 5:15--his research considers how networks can be most useful to DH projects. 
Here's an overview: http://journalofdigitalhumanities.org/1-1/demystifying-networks-by-scott-weingart/

**Comment by mscuthbert** [comment]
Thanks for the work!
