### ISSUE TITLE
Network visualization — Force-directed graph

### ISSUE THREAD

**Issue by ltagliaferri** [dhmit/computation_hist#174]
Create network diagram to map all of the key players in correspondence

D3 example: https://observablehq.com/@d3/force-directed-graph

**Comment by mscuthbert** [comment]
Great -- see also #175

**Comment by erica02139** [comment]
See also discussion on #173

**Comment by erica02139** [comment]
Potentially useful: https://networkx.github.io

**Comment by ryaanahmed** [comment]
done! huge work by @samimak37 and @meesuekim
