### ISSUE TITLE
Fix advanced search

### ISSUE THREAD

**Issue by ifeife123** [dhmit/computation_hist#213]
Error message from choosing year out of range. This needs to be fixed as it causes the site to crash rather than telling the user to pick a correct date.

<img width="1214" alt="Screen Shot 2019-03-19 at 10 28 50 AM" src="https://user-images.githubusercontent.com/30591068/54613891-df329d80-4a31-11e9-8ad1-f379b4c196c0.png">

**Comment by elenaboal** [comment]
Fixed in pull request #219
