### ISSUE TITLE
Search "exactly this phrase" Google-style

### ISSUE THREAD

**Issue by equationcrunchor** [dhmit/computation_hist#224]
So searching `"machine learning"` would return results that contain the exact phrase `machine learning`, while searching for `machine learning` would return results that contain either `machine` or `learning`.

**Comment by ryaanahmed** [comment]
This is done for full text search on advanced_search, but we should generalize this code and apply it to all fields.

**Comment by ryaanahmed** [comment]
Now done for keyword search as well. Thanks to @Carol217 for fantastic work making our search feature better.
