### ISSUE TITLE
Fix metadata mistakes caught by populate_from_metadata

### ISSUE THREAD

**Issue by ryaanahmed** [dhmit/computation_hist#247]
Names in the metadata should have a single comma after the last name, and then be semicolon delimited.

Good:
`Morse, Philip M.`

Nope:
`Morse, Philip, M.`

Good:
`Last, First; AnotherLast, AnotherFirst`

Nope:
`Last, First, AnotherLast, AnotherFirst`

populate_from_metadata now prints an error message when it encounters a name that has too many commas: i.e., a name that is probably two names that were comma rather than semicolon delimited (second 'nope' example) OR a name where an extra comma was erroneously introduced (as in my first 'nope') example.

Examples:
```
There seem to be too many commas in this name  ['Brock', 'L. T.', 'Campbell', 'E.']
There seem to be too many commas in this name  ['Morse', 'Philip', 'M.']
```

**Comment by mscuthbert** [comment]
I think that @angcast is working on this using the difflib library to find very small differences among names to standardize them.

**Comment by ryaanahmed** [comment]
Comma errors all fixed; this is now superseded by https://github.com/dhmit/computation_hist/issues/351
