### ISSUE TITLE
Remove bare exceptions from archive.views

### ISSUE THREAD

**Issue by ryaanahmed** [dhmit/computation_hist#249]
No bare excepts, please! See

https://github.com/dhmit/computation_hist/blob/65825477afe5746756173a5915c2e506df272039/apps/archives/views.py#L39
and
https://github.com/dhmit/computation_hist/blob/65825477afe5746756173a5915c2e506df272039/apps/archives/views.py#L111

... and similar.

To safely retrieve a value from a dict if you don't know if the key exists, you can use get(), which returns a default value of None if it's not there, and then if on that.

Django doesn't have a nice way to do this for object.get, so an exception is fine there, but please catch the correct exception. See: https://docs.djangoproject.com/en/2.1/ref/models/querysets/#django.db.models.query.QuerySet.get

(for more on why this is not good practice: https://realpython.com/the-most-diabolical-python-antipattern/)

**Comment by Carol217** [comment]
done!
