### ISSUE TITLE
Team Page

### ISSUE THREAD

**Issue by ltagliaferri** [dhmit/computation_hist#283]
We don't have a team page. The Gender / Novels project includes a team page which was linked to in the Ms. Magazine article. I think it is important to recognize the work of all the contributors.

**Comment by ltagliaferri** [comment]
Also should add info about the [MIT Archives](https://libraries.mit.edu/archives/), and a longer description about the project.

**Comment by ifeife123** [comment]
I believe this is the same as issue #370 so I'm closing this issue
