### ISSUE TITLE
Labeling of Folders in Box 1

### ISSUE THREAD

**Issue by mgallegos3015** [dhmit/computation_hist#287]
The numerical labeling of the folders in Box one does not always match the number of the folder. For example, 13 is mapped to folder 14. This particular pattern of the numerical label mapped to the next folder continues until 19 is mapped to 20. However, after this the mismatch in labeling and folder number follows no pattern although folders 21-30 all appear to be there but are simply in the wrong order.

**Comment by mscuthbert** [comment]
There was a folder missing in the archive (perhaps restricted?) and I think it was the original folder 13.  This would explain it, but doesn't go to a solution.

**Comment by ryaanahmed** [comment]
I think we fixed this.
@srisi @erica02139  --  someone sanity check me?

**Comment by srisi** [comment]
I don't know if/who fixed it but it seems correct now.

**Comment by ryaanahmed** [comment]
Thought so. Closing.
