### ISSUE TITLE
Opening Stories

### ISSUE THREAD

**Issue by mgallegos3015** [dhmit/computation_hist#288]
Stories only open when you click on their image.

**Comment by mscuthbert** [comment]
Can you give a preferred solution?  What should someone work on having it do?  Thanks!

**Comment by mgallegos3015** [comment]
Ideally the stories would open if any part of them(the image or the teaser) was clicked.

**Comment by ryaanahmed** [comment]
Assigning this to @Mayowa99, who's been working on the front page lately.

**Comment by Mayowa99** [comment]
That's already the case, both the teaser and the image are links. I can make the title a link too

**Comment by ryaanahmed** [comment]
done via https://github.com/dhmit/computation_hist/pull/321
thanks @Mayowa99 !
