### ISSUE TITLE
Doc Pages don't display in Microsoft Edge

### ISSUE THREAD

**Issue by Carol217** [dhmit/computation_hist#314]
They display just fine in Chrome, but in Microsoft edge a page like http://localhost:8000/archives/doc/271 just contains a box

**Comment by ryaanahmed** [comment]
I'm actually having a problem viewing them in Chrome on macOS, as well. I'm adding Ife to this issue, as she and I were looking at it the other day. Will investigate...

**Comment by Carol217** [comment]
![image](https://user-images.githubusercontent.com/23636809/57155277-08707880-6da9-11e9-99ef-25c83ec6a26f.png)

**Comment by Carol217** [comment]
![image](https://user-images.githubusercontent.com/23636809/57155326-29d16480-6da9-11e9-8cf2-e05e979679a3.png)

**Comment by ryaanahmed** [comment]
Well, at least it’s an error message that I wrote... there’s a check in ext/pdfjs/web/viewer.js  to make sure that the URL of the PDF is on our S3 bucket. Could be that the urls are heterogenous and the check I wrote is wrong.

Is this happening on all docs or just some?

**Comment by Carol217** [comment]
All docs on Microsoft Edge

Get Outlook for Android<https://aka.ms/ghei36>




On Fri, May 3, 2019 at 2:09 PM -0400, "Ryaan Ahmed" <notifications@github.com<mailto:notifications@github.com>> wrote:


Well, at least it’s an error message that I wrote... there’s a check in ext/pdfjs/web/viewer.js to make sure that the URL of the PDF is on our S3 bucket. Could be that the urls are heterogenous and the check I wrote is wrong.

Is this happening on all docs or just some?

**Comment by ryaanahmed** [comment]
Weird. I'll take a look on a Windows computer on Monday. A quick search shows a bunch of issues around PDF.js on Edge, so maybe it's not the solution for that browser...

Does this demo load for you on Edge? https://mozilla.github.io/pdf.js/web/viewer.html

**Comment by Carol217** [comment]
@ryaanahmed , yeah, it does. As of now, the Edge pdf display is still not functioning

**Comment by ryaanahmed** [comment]
fixed via https://github.com/dhmit/computation_hist/pull/389
