### ISSUE TITLE
Unify advanced_search and search_results views

### ISSUE THREAD

**Issue by ryaanahmed** [dhmit/computation_hist#320]
In apps.archives.views, we currently have two search views:

- `advanced_search`, which is a document-only search with lots of filtering options
- `search_results`, which searches over all of our models, but has limited options

Let's combine these into one master search. Ideas (based on email discussions between @angcast @Carol217 @mscuthbert and @ryaanahmed)...

- Let's use `advanced_search` as the basis of the unified search page, as it's now much more robust than the simple search implemented in `search_results`.
- We don't need to search across all models: let's focus on people and documents.

Steps:
- [x] Update advanced_search to include search over people in addition to documents
- [x] Wire the search field in the navbar up to `advanced_search` and get rid of `search_results`
- [x] Rename `advanced_search` to just `search` (yay!)
- [x] When no search term is given, show _no_ results, rather than showing _all_ docs.
- [ ] (Probably) add options to advanced_search to search for _either_ documents or people, and hide the advanced options for documents or people depending on what kind of advanced search the user wants

I'm going to make a start at wiring some of this up right now—will push to a branch called `unify_search`. Let's collaborate on this branch to get this done!

**Comment by ryaanahmed** [comment]
@mscuthbert points out:

> Looking at a name that intrigued me when I searched first, “Cuthbert” — when I do a Search, I get all the letters that Cuthbert Hurd wrote and also those that were written to him.  When I do a “Keyword” search — then it misses the ones he wrote.  When I do an Author search it misses the ones that were written to him.  I think that we want to have one place to find all of these things, and that this place should be the most obvious place, which would probably be the big search bar at the top.  :-)

We should investigate the "Keyword" search problem here, as I'm pretty sure that should be working already... must be a bug in there.

**Comment by ryaanahmed** [comment]
Pushed an initial rough-in of some of this to `unify_search`. LOTS left to be done.

**Comment by ryaanahmed** [comment]
Referencing https://github.com/dhmit/computation_hist/issues/326 here — as soon as we wire up advanced_search to the main search box and get rid of the old search_results view, that issue goes away, as case-insensitive search is already implemented in advanced_search.

**Comment by angcast** [comment]
I updated the css file to display people with the same box as documents when searching for a keyword. This box shows up on Microsoft Edge, but it does not show up on google chrome. I am not sure why. I was wondering if it shows up for you guys.
![image](https://user-images.githubusercontent.com/46508885/56911240-7c91e000-6a7a-11e9-883f-fd75ff3034b6.png)

**Comment by ryaanahmed** [comment]
Works fine for me on Chrome. Did you try a hard refresh? Might be that Chrome had the old CSS cached.

**Comment by Carol217** [comment]
curiously enough, it doesn't show up on my chrome either. nor does it show up on Microsoft edge? I might have modified the files before you finish committing them, in which case, my sincerest apologies...

**Comment by ryaanahmed** [comment]
Great progress so far!

Just checked again, and the boxes show up on all browsers on my machine... are you both absolutely sure you tried with a hard refresh / cache clear?

**Comment by ryaanahmed** [comment]
Search no longer gives results when the user inputs nothing in the search box or the advanced search fields. We should probably have front end validation for this as well, as well as some kind of error message if no fields are filled in.

**Comment by ryaanahmed** [comment]
Did a few things this morning:
- merged the search facets branch into our `unify_search` branch,
- split process_search and generate_search_facets out into their own file (apps/archives/search.py) just to keep things organized
- did a little tidy up on the search template

**Comment by ryaanahmed** [comment]
I sketched in a basic structure to add refine search based on the search facets. Might be able to finish this up later today, but if someone else wants to work on it, just drop me a note on Slack first to make sure that I'm not also working on it!

**Comment by ryaanahmed** [comment]
Closing this, as the main work is done, and this has been superseded by a later issue opened by Carol. Great progress here!
