### ISSUE TITLE
Search results should be case insensitive

### ISSUE THREAD

**Issue by mscuthbert** [dhmit/computation_hist#326]
Compare "Cuthbert" to "cuthbert" in Search 

Unchecked if applies to Advanced Search also...

**Comment by srisi** [comment]
Maybe we should just fold the search into the advanced search.

**Comment by mscuthbert** [comment]
@angcast and @ryaanahmed are working on this actively!  When that happens, this problem will go away.  Works great on Advanced Search.

**Comment by Carol217** [comment]
it's also been fixed for just search a while back, hidden among my many commits ^^
