### ISSUE TITLE
Add reference to our GitHub to the site

### ISSUE THREAD

**Issue by ryaanahmed** [dhmit/computation_hist#344]
Something like what we have on the Gender Novels project.

**Comment by ifeife123** [comment]
Resolved

**Comment by ryaanahmed** [comment]
I'm reopening this issue -- with the number of partner organizations etc. in the bottom navbar, it's getting a bit crammed. I suggest that we instead put a link to our code on the project about page, and make it more explicit than just having the Github logo in the corner.

**Comment by ryaanahmed** [comment]
@Mayowa99 @ifeife123 @rikitabansal -- can someone add this to the blurb at the top of the "Our Team" page?

**Comment by rikitabansal** [comment]
resolved
