### ISSUE TITLE
Create additional Selenium tests

### ISSUE THREAD

**Issue by ryaanahmed** [dhmit/computation_hist#346]
Huge thanks to @Carol217 for already taking initiative on this...

TODO:
- [x] Create a `SeleniumTestCase` subclass for sims in `apps.simulations.tests` (following the example of the one in archives)
- [x] All simulations pages need tests, just to make sure they load without 404ing
- [x] Tests that click on each button in the Simulation demos and make sure they don't throw errors
- [x] Click a story on the home page, make sure link works

Probably more... keep jotting test coverage ideas on this issue, which we'll use as a tracker.

**Comment by Carol217** [comment]
resolved until new cases arise
