### ISSUE TITLE
Weird Formatting in Search Results

### ISSUE THREAD

**Issue by equationcrunchor** [dhmit/computation_hist#349]
Example:
![image](https://user-images.githubusercontent.com/43281248/56928597-52094c80-6aa5-11e9-9bda-0235f0a232a6.png)

**Comment by ryaanahmed** [comment]
The main problem is the space after the colon (which is causing the text wrap and weirdness for, e.g., the 'Recipient' field here). I'd suggest we remove the colon, anyway: the bold / not bold distinction makes what is the label and what is the content clear.
