### ISSUE TITLE
Search Augmentation - Time and Refinement

### ISSUE THREAD

**Issue by Carol217** [dhmit/computation_hist#367]
> search takes a few seconds to return results
> clicking on additional refinement options replaces the old ones, rather than continues to specify the search
- [ ] speed up search
- [x] let refine actually narrow down options

**Comment by Carol217** [comment]
Update: AND search has been created in order to deal with refinement issues, but it only applies to fields relating to people/organizations (author, recipient, cced). I can expand it to the other fields if that'll further improve our search, so let me know.

Searching is still slow as heck, however

**Comment by ryaanahmed** [comment]
@Carol217 - did you make a PR / merge this?

Also adding this from our last issue:
- [ ] Add options to advanced_search to search for either documents or people, and hide the advanced options for documents or people depending on what kind of advanced search the user wants

I really like how this is handled on the MIT libraries page:

<img width="805" alt="Annotation 2019-05-10 115927" src="https://user-images.githubusercontent.com/691117/57540620-1a0ece80-731b-11e9-8a47-0a2fdef0e476.png">

So, we'd have tabs: "All", "Documents", "People".

**Comment by ryaanahmed** [comment]
Closing this:
- we decided not to refine by people or docs
- searching is actually fast enough for most things (except with lots of results like "Morse"), and @Carol217 implemented a loading spinner, so it's clear that something is happening when you hit search
