### ISSUE TITLE
Dropdown does not work on document pages

### ISSUE THREAD

**Issue by srisi** [dhmit/computation_hist#368]
Currently, clicking on the "Archives" tab when looking at a document (e.g. http://127.0.0.1:8000/archives/doc/2_20_ershov_16) does not toggle the dropdown.
My guess is that this is related to pdf.js because it still works with branches that have not been updated for two or more days.

**Comment by felixtran39** [comment]
There also seems to be a problem with the sidebar not showing up anymore either.

**Comment by ryaanahmed** [comment]
Fixed via https://github.com/dhmit/computation_hist/pull/380

super dumb bug by yours truly.
