### ISSUE TITLE
Finish about page

### ISSUE THREAD

**Issue by angcast** [dhmit/computation_hist#370]
A page that describes our journey throughout the project and has every team member on it.

**Comment by mscuthbert** [comment]
@Mayowa99 has also been working on this.

**Comment by ryaanahmed** [comment]
Great progress on this so far, but we still need some additional copy. We still need this:

> Also should add info about the [MIT Archives](https://libraries.mit.edu/archives/), and a longer description about the project.
_Originally posted by @ltagliaferri in https://github.com/dhmit/computation_hist/issues/283#issuecomment-484977637_

Maybe we change the title "Our Team" to "About", so we can include this material and also reference to our code etc.

**Comment by ryaanahmed** [comment]
@mscuthbert - should we also add our collaborators from the Archives to the about page?

**Comment by ryaanahmed** [comment]
See also https://github.com/dhmit/computation_hist/issues/344

**Comment by mscuthbert** [comment]
Definitely!!!!!!!!!!!

Best,
Michael

---
Sent from a phone (413-575-6024)
Apologies for typos or general brevity

On May 10, 2019, at 18:01, Ryaan Ahmed <notifications@github.com<mailto:notifications@github.com>> wrote:


@mscuthbert<https://github.com/mscuthbert> - should we also add our collaborators from the Archives to the about page?

**Comment by angcast** [comment]
Changed Our team ---> About Us

**Comment by angcast** [comment]
Currently writing a story about the lab; I added @erica02139 onto this issue because she is going to help us  with the credit portion of it

**Comment by erica02139** [comment]
Great! Also, the Archives will be termed the "Department of Distinctive Collections," starting Monday.

**Comment by ryaanahmed** [comment]
Things left to do:
- [ ] Add librarians / archivists to the page
- [ ] Edits to the text above the fold; see:
I think I would reframe some of this to showcase the project and the entire team, and how it intersects with SHASS, Mellon, the libraries, etc. I can work on this though
_Originally posted by @ltagliaferri in https://github.com/dhmit/computation_hist/pull/406_
- [ ] Update references to the Archives with their new name "Department of Distinctive Collections" -- can we get some graphics from them on this? (maybe @mscuthbert ask, since you're meeting them this week?)

**Comment by ryaanahmed** [comment]
Who wants to contact the relevant folks from the archives to get headshots that we can add to the "Our Team" section of the page?

**Comment by mscuthbert** [comment]
I'm happy do it -- sometimes libraries wish to keep their privacy close to hand so I want the connection to be offered as an opportunity if they want it rather than something they need to do.

**Comment by ryaanahmed** [comment]
Great, so @mscuthbert, let's have you take point on interfacing with the Dept of Distinctive Collections about both their preferences for credit on our site and getting any graphics from them that they might want us to use as part of that credit.

**Comment by Mayowa99** [comment]
I still need about three more responses for the survey I sent out from current lab members. What should I put for job descriptions of the previous members?

**Comment by ryaanahmed** [comment]
done! via https://github.com/dhmit/computation_hist/pull/461
