### ISSUE TITLE
Folder display page sorted incorrectly

### ISSUE THREAD

**Issue by ifeife123** [dhmit/computation_hist#386]
<img width="1436" alt="Screen Shot 2019-05-07 at 11 12 08 AM" src="https://user-images.githubusercontent.com/30591068/57311147-1845d080-70b9-11e9-8e41-bbc78078450a.png">
This shows the last item to be of index 15 in this folder:
If you look at the url it is actually at index 9, thus not the 15th and not the last item in the folder:
<img width="1440" alt="Screen Shot 2019-05-07 at 11 13 41 AM" src="https://user-images.githubusercontent.com/30591068/57311266-4b885f80-70b9-11e9-836b-2d09dc88954e.png">

**Comment by ryaanahmed** [comment]
Didn't you fix this already via https://github.com/dhmit/computation_hist/pull/383? Or are you pointing out a different issue?

**Comment by ryaanahmed** [comment]
We're sorting now, but incorrectly: the sort is on the file_name field, which means that it's in alpha order: 1, 10, 11, 12, ..., 2, 21, 22, 23...

**Comment by ryaanahmed** [comment]
Fixed via https://github.com/dhmit/computation_hist/pull/398
