### ISSUE TITLE
Unify design across the site

### ISSUE THREAD

**Issue by ryaanahmed** [dhmit/computation_hist#401]
We have a bit of a mishmash of styles, fonts, colors, etc. that we need to unify across the whole project in order to look consistent and professional. Here are the big issues that I see:

- [x] We have a pattern of divs on the page having their own background color, which is nice, but the color is inconsistent. On the 'search' page, it's grey, on most of the archives list pages, it's white. Let's go with white; I think this pops better. We can also add this to the simulations, as a background for the three main panels ("Code", "General Memory", "Other Registers") to make them stand out more.

- [x] We have a mix of sharp and rounded corner elements. Bootstrap does rounded corners by default on buttons etc. but I think that the sharp corners look better with our overall design. Let's make everything sharp. So, e.g., the navbar's search field and button; on the search page the document type selector; etc. etc.

- [x] Inconsistent font sizes throughout. Compare, e.g., http://comphist-test.digitalhumanitiesmit.org/simulations/ and http://comphist-test.digitalhumanitiesmit.org/archives/browse/ -- exactly the same design, so we should unify the font sizes.
- [x] Also see the "Our Team" page -- there are subheaders that don't use our header font.

- [x] The white frame pattern from the "Our Team" page looks really good. Can we apply that to all images across the site? So: the story teasers, and also probably the images in the stories.

- [x] padding and margins are inconsistent throughout. Let's try and unify.

- [x] make a consistent link colour

There are a TON of little things, so let's keep our eyes open and tidy all of this up, so we have a professional presentation.

**Comment by ifeife123** [comment]
working on this issue in the [template cleanup](https://github.com/dhmit/computation_hist/tree/template_cleanup) branch

**Comment by angcast** [comment]
Fixed header issue in About Us on the branch we are working on (-ourteam)

**Comment by ifeife123** [comment]
> We can also add this to the simulations, as a background for the three main panels ("Code", "General Memory", "Other Registers") to make them stand out more.

We should also add text wrapping
- waiting for @equationcrunchor to finish edits on simulator

**Comment by Mayowa99** [comment]
added borders to all of the images and fixed the links on the template cleanup branch

**Comment by ryaanahmed** [comment]
Almost done! Just need to add panel-i-fy sims (will hit this afternoon) and then we're pretty much good to go in terms of design polish.

**Comment by ryaanahmed** [comment]
> We should also add text wrappingwaiting for @equationcrunchor to finish edits on simulator

Talked to @equationcrunchor, and it probably makes the registers incomprehensible if text-wrapped. We discussed another solution (moving the rightmost panel to a wider panel below), but this is not urgent. Let's call this a no-op for now.

**Comment by ryaanahmed** [comment]
done via https://github.com/dhmit/computation_hist/pull/438
thanks all!
